runs:
  using: composite

  steps:
    - uses: oven-sh/setup-bun@v2

    - name: Install dependencies
      run: bun install --frozen-lockfile
      shell: bash # Composite jobs must specify the shell.
